2016_nfl_players = [
 {
   "rank": 1,
   "name": "Antonio Brown",
   "position": "WR",
   "positionRank": "WR1",
   "team": "PIT",
   "bye": 8,
   "age": "",
   "pts": 92.16,
   "adp": "1",
   "vbd": 44.32
 },
 {
   "rank": 2,
   "name": "Todd Gurley",
   "position": "RB",
   "positionRank": "RB1",
   "team": "LA",
   "bye": 8,
   "age": "",
   "pts": 90.72,
   "adp": "2",
   "vbd": 41.03
 },
 {
   "rank": 3,
   "name": "David Johnson",
   "position": "RB",
   "positionRank": "RB2",
   "team": "ARI",
   "bye": 9,
   "age": "",
   "pts": 88.48,
   "adp": "3",
   "vbd": 38.79
 },
 {
   "rank": 4,
   "name": "Julio Jones",
   "position": "WR",
   "positionRank": "WR2",
   "team": "ATL",
   "bye": 11,
   "age": "",
   "pts": 86.24,
   "adp": "5",
   "vbd": 38.4
 },
 {
   "rank": 5,
   "name": "Odell Beckham Jr",
   "position": "WR",
   "positionRank": "WR3",
   "team": "NYG",
   "bye": 8,
   "age": "",
   "pts": 85.18,
   "adp": "4",
   "vbd": 37.34
 },
 {
   "rank": 6,
   "name": "Tyler Lockett",
   "position": "WR",
   "positionRank": "WR4",
   "team": "SEA",
   "bye": 5,
   "age": "",
   "pts": 84.16,
   "adp": "6",
   "vbd": 36.32
 },
 {
   "rank": 7,
   "name": "Ezekiel Elliott",
   "position": "RB",
   "positionRank": "RB3",
   "team": "DAL",
   "bye": 7,
   "age": "",
   "pts": 82.72,
   "adp": "8",
   "vbd": 33.03
 },
 {
   "rank": 8,
   "name": "Adrian Peterson",
   "position": "RB",
   "positionRank": "RB4",
   "team": "MIN",
   "bye": 6,
   "age": "",
   "pts": 82.04,
   "adp": "7",
   "vbd": 32.35
 },
 {
   "rank": 9,
   "name": "Rob Gronkowski",
   "position": "TE",
   "positionRank": "TE1",
   "team": "NE",
   "bye": 9,
   "age": "",
   "pts": 68.45,
   "adp": "9",
   "vbd": 32.54
 },
 {
   "rank": 10,
   "name": "Lamar Miller",
   "position": "RB",
   "positionRank": "RB5",
   "team": "HOU",
   "bye": 9,
   "age": "",
   "pts": 78.88,
   "adp": "10",
   "vbd": 29.19
 },
 {
   "rank": 11,
   "name": "Jamaal Charles",
   "position": "RB",
   "positionRank": "RB6",
   "team": "KC",
   "bye": 5,
   "age": "",
   "pts": 78.84,
   "adp": "12",
   "vbd": 29.15
 },
 {
   "rank": 12,
   "name": "DeAndre Hopkins",
   "position": "WR",
   "positionRank": "WR5",
   "team": "HOU",
   "bye": 9,
   "age": "",
   "pts": 76.32,
   "adp": "13",
   "vbd": 28.48
 },
 {
   "rank": 13,
   "name": "A.J. Green",
   "position": "WR",
   "positionRank": "WR6",
   "team": "CIN",
   "bye": 9,
   "age": "",
   "pts": 75.52,
   "adp": "14",
   "vbd": 27.68
 },
 {
   "rank": 14,
   "name": "Cam Newton",
   "position": "QB",
   "positionRank": "QB1",
   "team": "CAR",
   "bye": 7,
   "age": "",
   "pts": 125.52,
   "adp": "11",
   "vbd": 27.89
 },
 {
   "rank": 15,
   "name": "LeVeon Bell",
   "position": "RB",
   "positionRank": "RB7",
   "team": "PIT",
   "bye": 8,
   "age": "",
   "pts": 75.11,
   "adp": "15",
   "vbd": 25.41
 },
 {
   "rank": 16,
   "name": "Devonta Freeman",
   "position": "RB",
   "positionRank": "RB8",
   "team": "ATL",
   "bye": 11,
   "age": "",
   "pts": 74.88,
   "adp": "16",
   "vbd": 25.19
 },
 {
   "rank": 17,
   "name": "Mark Ingram",
   "position": "RB",
   "positionRank": "RB9",
   "team": "NO",
   "bye": 5,
   "age": "",
   "pts": 74.61,
   "adp": "18",
   "vbd": 24.92
 },
 {
   "rank": 18,
   "name": "Doug Martin",
   "position": "RB",
   "positionRank": "RB10",
   "team": "TB",
   "bye": 6,
   "age": "",
   "pts": 73.72,
   "adp": "17",
   "vbd": 24.03
 },
 {
   "rank": 19,
   "name": "Allen Robinson",
   "position": "WR",
   "positionRank": "WR7",
   "team": "JAX",
   "bye": 5,
   "age": "",
   "pts": 69.12,
   "adp": "21",
   "vbd": 21.28
 },
 {
   "rank": 20,
   "name": "Eddie Lacy",
   "position": "RB",
   "positionRank": "RB11",
   "team": "GB",
   "bye": 4,
   "age": "",
   "pts": 70.84,
   "adp": "19",
   "vbd": 21.15
 },
 {
   "rank": 21,
   "name": "Dez Bryant",
   "position": "WR",
   "positionRank": "WR8",
   "team": "DAL",
   "bye": 7,
   "age": "",
   "pts": 68.42,
   "adp": "22",
   "vbd": 20.58
 },
 {
   "rank": 22,
   "name": "LeSean McCoy",
   "position": "RB",
   "positionRank": "RB12",
   "team": "BUF",
   "bye": 10,
   "age": "",
   "pts": 70.29,
   "adp": "20",
   "vbd": 20.6
 },
 {
   "rank": 23,
   "name": "Brandon Marshall",
   "position": "WR",
   "positionRank": "WR9",
   "team": "NYJ",
   "bye": 11,
   "age": "",
   "pts": 67.3,
   "adp": "23",
   "vbd": 19.46
 },
 {
   "rank": 24,
   "name": "Jordy Nelson",
   "position": "WR",
   "positionRank": "WR10",
   "team": "GB",
   "bye": 4,
   "age": "",
   "pts": 66.69,
   "adp": "25",
   "vbd": 18.85
 },
 {
   "rank": 25,
   "name": "C.J. Anderson",
   "position": "RB",
   "positionRank": "RB13",
   "team": "DEN",
   "bye": 11,
   "age": "",
   "pts": 68.44,
   "adp": "24",
   "vbd": 18.75
 },
 {
   "rank": 26,
   "name": "Russell Wilson",
   "position": "QB",
   "positionRank": "QB2",
   "team": "SEA",
   "bye": 5,
   "age": "",
   "pts": 116.24,
   "adp": "26",
   "vbd": 18.61
 },
 {
   "rank": 27,
   "name": "T.Y. Hilton",
   "position": "WR",
   "positionRank": "WR11",
   "team": "IND",
   "bye": 10,
   "age": "",
   "pts": 65.6,
   "adp": "30",
   "vbd": 17.76
 },
 {
   "rank": 28,
   "name": "Mike Evans",
   "position": "WR",
   "positionRank": "WR12",
   "team": "TB",
   "bye": 6,
   "age": "",
   "pts": 64.86,
   "adp": "28",
   "vbd": 17.02
 },
 {
   "rank": 29,
   "name": "Alshon Jeffery",
   "position": "WR",
   "positionRank": "WR13",
   "team": "CHI",
   "bye": 9,
   "age": "",
   "pts": 64.74,
   "adp": "29",
   "vbd": 16.9
 },
 {
   "rank": 30,
   "name": "Latavius Murray",
   "position": "RB",
   "positionRank": "RB14",
   "team": "OAK",
   "bye": 10,
   "age": "",
   "pts": 66.4,
   "adp": "27",
   "vbd": 16.71
 },
 {
   "rank": 31,
   "name": "Keenan Allen",
   "position": "WR",
   "positionRank": "WR14",
   "team": "SD",
   "bye": 11,
   "age": "",
   "pts": 63.78,
   "adp": "34",
   "vbd": 15.94
 },
 {
   "rank": 32,
   "name": "Aaron Rodgers",
   "position": "QB",
   "positionRank": "QB3",
   "team": "GB",
   "bye": 4,
   "age": "",
   "pts": 114.32,
   "adp": "33",
   "vbd": 16.69
 },
 {
   "rank": 33,
   "name": "Carlos Hyde",
   "position": "RB",
   "positionRank": "RB15",
   "team": "SF",
   "bye": 8,
   "age": "",
   "pts": 65.17,
   "adp": "37",
   "vbd": 15.48
 },
 {
   "rank": 34,
   "name": "Matt Forte",
   "position": "RB",
   "positionRank": "RB15",
   "team": "NYJ",
   "bye": 11,
   "age": "",
   "pts": 65.17,
   "adp": "31",
   "vbd": 15.48
 },
 {
   "rank": 35,
   "name": "Jarvis Landry",
   "position": "WR",
   "positionRank": "WR15",
   "team": "MIA",
   "bye": 8,
   "age": "",
   "pts": 63.04,
   "adp": "40",
   "vbd": 15.2
 },
 {
   "rank": 36,
   "name": "Amari Cooper",
   "position": "WR",
   "positionRank": "WR15",
   "team": "OAK",
   "bye": 10,
   "age": "",
   "pts": 63.04,
   "adp": "36",
   "vbd": 15.2
 },
 {
   "rank": 37,
   "name": "Demaryius Thomas",
   "position": "WR",
   "positionRank": "WR15",
   "team": "DEN",
   "bye": 11,
   "age": "",
   "pts": 63.04,
   "adp": "39",
   "vbd": 15.2
 },
 {
   "rank": 38,
   "name": "Thomas Rawls",
   "position": "RB",
   "positionRank": "RB17",
   "team": "SEA",
   "bye": 5,
   "age": "",
   "pts": 64.85,
   "adp": "32",
   "vbd": 15.16
 },
 {
   "rank": 39,
   "name": "Brandin Cooks",
   "position": "WR",
   "positionRank": "WR18",
   "team": "NO",
   "bye": 5,
   "age": "",
   "pts": 62.4,
   "adp": "43",
   "vbd": 14.56
 },
 {
   "rank": 40,
   "name": "Sammy Watkins",
   "position": "WR",
   "positionRank": "WR19",
   "team": "BUF",
   "bye": 10,
   "age": "",
   "pts": 62.16,
   "adp": "42",
   "vbd": 14.32
 },
 {
   "rank": 41,
   "name": "Melvin Gordon",
   "position": "RB",
   "positionRank": "RB18",
   "team": "SD",
   "bye": 11,
   "age": "",
   "pts": 63.52,
   "adp": "38",
   "vbd": 13.83
 },
 {
   "rank": 42,
   "name": "Ted Ginn",
   "position": "WR",
   "positionRank": "WR20",
   "team": "CAR",
   "bye": 7,
   "age": "",
   "pts": 61.12,
   "adp": "44",
   "vbd": 13.28
 },
 {
   "rank": 43,
   "name": "Jordan Reed",
   "position": "TE",
   "positionRank": "TE2",
   "team": "WAS",
   "bye": 9,
   "age": "",
   "pts": 49.41,
   "adp": "35",
   "vbd": 13.51
 },
 {
   "rank": 44,
   "name": "Greg Olsen",
   "position": "TE",
   "positionRank": "TE3",
   "team": "CAR",
   "bye": 7,
   "age": "",
   "pts": 48.64,
   "adp": "41",
   "vbd": 12.74
 },
 {
   "rank": 45,
   "name": "Andrew Luck",
   "position": "QB",
   "positionRank": "QB4",
   "team": "IND",
   "bye": 10,
   "age": "",
   "pts": 109.92,
   "adp": "46",
   "vbd": 12.29
 },
 {
   "rank": 46,
   "name": "Randall Cobb",
   "position": "WR",
   "positionRank": "WR21",
   "team": "GB",
   "bye": 4,
   "age": "",
   "pts": 58.78,
   "adp": "49",
   "vbd": 10.94
 },
 {
   "rank": 47,
   "name": "Jeremy Maclin",
   "position": "WR",
   "positionRank": "WR22",
   "team": "KC",
   "bye": 5,
   "age": "",
   "pts": 58.62,
   "adp": "51",
   "vbd": 10.78
 },
 {
   "rank": 48,
   "name": "Travis Kelce",
   "position": "TE",
   "positionRank": "TE4",
   "team": "KC",
   "bye": 5,
   "age": "",
   "pts": 46.77,
   "adp": "45",
   "vbd": 10.87
 },
 {
   "rank": 49,
   "name": "Ryan Mathews",
   "position": "RB",
   "positionRank": "RB19",
   "team": "PHI",
   "bye": 4,
   "age": "",
   "pts": 59.89,
   "adp": "48",
   "vbd": 10.19
 },
 {
   "rank": 50,
   "name": "Markus Wheaton",
   "position": "WR",
   "positionRank": "WR23",
   "team": "PIT",
   "bye": 8,
   "age": "",
   "pts": 57.44,
   "adp": "56",
   "vbd": 9.6
 },
 {
   "rank": 51,
   "name": "Jeremy Hill",
   "position": "RB",
   "positionRank": "RB20",
   "team": "CIN",
   "bye": 9,
   "age": "",
   "pts": 59.52,
   "adp": "47",
   "vbd": 9.83
 },
 {
   "rank": 52,
   "name": "Ameer Abdullah",
   "position": "RB",
   "positionRank": "RB21",
   "team": "DET",
   "bye": 10,
   "age": "",
   "pts": 59.09,
   "adp": "50",
   "vbd": 9.4
 },
 {
   "rank": 53,
   "name": "Jonathan Stewart",
   "position": "RB",
   "positionRank": "RB22",
   "team": "CAR",
   "bye": 7,
   "age": "",
   "pts": 58.26,
   "adp": "52",
   "vbd": 8.57
 },
 {
   "rank": 54,
   "name": "Tavon Austin",
   "position": "WR",
   "positionRank": "WR24",
   "team": "LA",
   "bye": 8,
   "age": "",
   "pts": 56.06,
   "adp": "61",
   "vbd": 8.22
 },
 {
   "rank": 55,
   "name": "Doug Baldwin",
   "position": "WR",
   "positionRank": "WR25",
   "team": "SEA",
   "bye": 5,
   "age": "",
   "pts": 55.9,
   "adp": "55",
   "vbd": 8.06
 },
 {
   "rank": 56,
   "name": "Golden Tate",
   "position": "WR",
   "positionRank": "WR26",
   "team": "DET",
   "bye": 10,
   "age": "",
   "pts": 55.68,
   "adp": "59",
   "vbd": 7.84
 },
 {
   "rank": 57,
   "name": "Eric Decker",
   "position": "WR",
   "positionRank": "WR27",
   "team": "NYJ",
   "bye": 11,
   "age": "",
   "pts": 55.58,
   "adp": "60",
   "vbd": 7.74
 },
 {
   "rank": 58,
   "name": "Jeremy Langford",
   "position": "RB",
   "positionRank": "RB23",
   "team": "CHI",
   "bye": 9,
   "age": "",
   "pts": 57.28,
   "adp": "57",
   "vbd": 7.59
 },
 {
   "rank": 59,
   "name": "Delanie Walker",
   "position": "TE",
   "positionRank": "TE5",
   "team": "TEN",
   "bye": 13,
   "age": "",
   "pts": 43.89,
   "adp": "53",
   "vbd": 7.99
 },
 {
   "rank": 60,
   "name": "DeMarco Murray",
   "position": "RB",
   "positionRank": "RB24",
   "team": "TEN",
   "bye": 13,
   "age": "",
   "pts": 57.08,
   "adp": "54",
   "vbd": 7.39
 },
 {
   "rank": 61,
   "name": "Drew Brees",
   "position": "QB",
   "positionRank": "QB5",
   "team": "NO",
   "bye": 5,
   "age": "",
   "pts": 105.04,
   "adp": "65",
   "vbd": 7.41
 },
 {
   "rank": 62,
   "name": "Duke Johnson",
   "position": "RB",
   "positionRank": "RB25",
   "team": "CLE",
   "bye": 13,
   "age": "",
   "pts": 56.16,
   "adp": "63",
   "vbd": 6.47
 },
 {
   "rank": 63,
   "name": "Travis Benjamin",
   "position": "WR",
   "positionRank": "WR28",
   "team": "SD",
   "bye": 11,
   "age": "",
   "pts": 53.92,
   "adp": "70",
   "vbd": 6.08
 },
 {
   "rank": 64,
   "name": "Giovani Bernard",
   "position": "RB",
   "positionRank": "RB26",
   "team": "CIN",
   "bye": 9,
   "age": "",
   "pts": 55.68,
   "adp": "64",
   "vbd": 5.99
 },
 {
   "rank": 65,
   "name": "Frank Gore",
   "position": "RB",
   "positionRank": "RB27",
   "team": "IND",
   "bye": 10,
   "age": "",
   "pts": 55.48,
   "adp": "69",
   "vbd": 5.79
 },
 {
   "rank": 66,
   "name": "Donte Moncrief",
   "position": "WR",
   "positionRank": "WR29",
   "team": "IND",
   "bye": 10,
   "age": "",
   "pts": 53.28,
   "adp": "73",
   "vbd": 5.44
 },
 {
   "rank": 67,
   "name": "Larry Fitzgerald",
   "position": "WR",
   "positionRank": "WR29",
   "team": "ARI",
   "bye": 9,
   "age": "",
   "pts": 53.28,
   "adp": "72",
   "vbd": 5.44
 },
 {
   "rank": 68,
   "name": "Coby Fleener",
   "position": "TE",
   "positionRank": "TE6",
   "team": "NO",
   "bye": 5,
   "age": "",
   "pts": 42.13,
   "adp": "58",
   "vbd": 6.23
 },
 {
   "rank": 69,
   "name": "Michael Floyd",
   "position": "WR",
   "positionRank": "WR31",
   "team": "ARI",
   "bye": 9,
   "age": "",
   "pts": 53.18,
   "adp": "66",
   "vbd": 5.34
 },
 {
   "rank": 70,
   "name": "Blake Bortles",
   "position": "QB",
   "positionRank": "QB6",
   "team": "JAX",
   "bye": 5,
   "age": "",
   "pts": 103.6,
   "adp": "74",
   "vbd": 5.97
 },
 {
   "rank": 71,
   "name": "Zach Ertz",
   "position": "TE",
   "positionRank": "TE7",
   "team": "PHI",
   "bye": 4,
   "age": "",
   "pts": 41.71,
   "adp": "62",
   "vbd": 5.81
 },
 {
   "rank": 72,
   "name": "Tom Brady",
   "position": "QB",
   "positionRank": "QB7",
   "team": "NE",
   "bye": 9,
   "age": "",
   "pts": 102.99,
   "adp": "68",
   "vbd": 5.36
 },
 {
   "rank": 73,
   "name": "Matt Jones",
   "position": "RB",
   "positionRank": "RB28",
   "team": "WAS",
   "bye": 9,
   "age": "",
   "pts": 54.21,
   "adp": "71",
   "vbd": 4.51
 },
 {
   "rank": 74,
   "name": "Gary Barnidge",
   "position": "TE",
   "positionRank": "TE8",
   "team": "CLE",
   "bye": 13,
   "age": "",
   "pts": 40.8,
   "adp": "67",
   "vbd": 4.9
 },
 {
   "rank": 75,
   "name": "DeSean Jackson",
   "position": "WR",
   "positionRank": "WR32",
   "team": "WAS",
   "bye": 9,
   "age": "",
   "pts": 51.78,
   "adp": "77",
   "vbd": 3.94
 },
 {
   "rank": 76,
   "name": "Rashad Jennings",
   "position": "RB",
   "positionRank": "RB29",
   "team": "NYG",
   "bye": 8,
   "age": "",
   "pts": 52.98,
   "adp": "76",
   "vbd": 3.29
 },
 {
   "rank": 77,
   "name": "Antonio Gates",
   "position": "TE",
   "positionRank": "TE9",
   "team": "SD",
   "bye": 11,
   "age": "",
   "pts": 39.71,
   "adp": "78",
   "vbd": 3.8
 },
 {
   "rank": 78,
   "name": "Emmanuel Sanders",
   "position": "WR",
   "positionRank": "WR33",
   "team": "DEN",
   "bye": 11,
   "age": "",
   "pts": 50.56,
   "adp": "84",
   "vbd": 2.72
 },
 {
   "rank": 79,
   "name": "Julian Edelman",
   "position": "WR",
   "positionRank": "WR34",
   "team": "NE",
   "bye": 9,
   "age": "",
   "pts": 50.5,
   "adp": "82",
   "vbd": 2.66
 },
 {
   "rank": 80,
   "name": "DeVante Parker",
   "position": "WR",
   "positionRank": "WR35",
   "team": "MIA",
   "bye": 8,
   "age": "",
   "pts": 49.98,
   "adp": "86",
   "vbd": 2.14
 },
 {
   "rank": 81,
   "name": "Eli Manning",
   "position": "QB",
   "positionRank": "QB8",
   "team": "NYG",
   "bye": 8,
   "age": "",
   "pts": 100.56,
   "adp": "79",
   "vbd": 2.93
 },
 {
   "rank": 82,
   "name": "Kelvin Benjamin",
   "position": "WR",
   "positionRank": "WR36",
   "team": "CAR",
   "bye": 7,
   "age": "",
   "pts": 49.92,
   "adp": "81",
   "vbd": 2.08
 },
 {
   "rank": 83,
   "name": "Arian Foster",
   "position": "RB",
   "positionRank": "RB30",
   "team": "MIA",
   "bye": 8,
   "age": "",
   "pts": 51.9,
   "adp": "80",
   "vbd": 2.21
 },
 {
   "rank": 84,
   "name": "Corey Coleman",
   "position": "WR",
   "positionRank": "WR37",
   "team": "CLE",
   "bye": 13,
   "age": "",
   "pts": 49.76,
   "adp": "92",
   "vbd": 1.92
 },
 {
   "rank": 85,
   "name": "Tyler Eifert",
   "position": "TE",
   "positionRank": "TE10",
   "team": "CIN",
   "bye": 9,
   "age": "",
   "pts": 38.64,
   "adp": "75",
   "vbd": 2.73
 },
 {
   "rank": 86,
   "name": "Jordan Matthews",
   "position": "WR",
   "positionRank": "WR38",
   "team": "PHI",
   "bye": 4,
   "age": "",
   "pts": 49.66,
   "adp": "87",
   "vbd": 1.82
 },
 {
   "rank": 87,
   "name": "John Brown",
   "position": "WR",
   "positionRank": "WR39",
   "team": "ARI",
   "bye": 9,
   "age": "",
   "pts": 49.63,
   "adp": "89",
   "vbd": 1.79
 },
 {
   "rank": 88,
   "name": "Isaiah Crowell",
   "position": "RB",
   "positionRank": "RB31",
   "team": "CLE",
   "bye": 13,
   "age": "",
   "pts": 51.68,
   "adp": "88",
   "vbd": 1.99
 },
 {
   "rank": 89,
   "name": "Carson Palmer",
   "position": "QB",
   "positionRank": "QB9",
   "team": "ARI",
   "bye": 9,
   "age": "",
   "pts": 99.95,
   "adp": "90",
   "vbd": 2.31
 },
 {
   "rank": 90,
   "name": "Ben Roethlisberger",
   "position": "QB",
   "positionRank": "QB10",
   "team": "PIT",
   "bye": 8,
   "age": "",
   "pts": 99.91,
   "adp": "94",
   "vbd": 2.27
 },
 {
   "rank": 91,
   "name": "Michael Crabtree",
   "position": "WR",
   "positionRank": "WR40",
   "team": "OAK",
   "bye": 10,
   "age": "",
   "pts": 49.28,
   "adp": "85",
   "vbd": 1.44
 },
 {
   "rank": 92,
   "name": "Julius Thomas",
   "position": "TE",
   "positionRank": "TE11",
   "team": "JAX",
   "bye": 5,
   "age": "",
   "pts": 38.17,
   "adp": "83",
   "vbd": 2.26
 },
 {
   "rank": 93,
   "name": "Allen Hurns",
   "position": "WR",
   "positionRank": "WR41",
   "team": "JAX",
   "bye": 5,
   "age": "",
   "pts": 49.12,
   "adp": "99",
   "vbd": 1.28
 },
 {
   "rank": 94,
   "name": "Jameis Winston",
   "position": "QB",
   "positionRank": "QB11",
   "team": "TB",
   "bye": 6,
   "age": "",
   "pts": 99.52,
   "adp": "93",
   "vbd": 1.89
 },
 {
   "rank": 95,
   "name": "Tyrod Taylor",
   "position": "QB",
   "positionRank": "QB12",
   "team": "BUF",
   "bye": 10,
   "age": "",
   "pts": 99.46,
   "adp": "91",
   "vbd": 1.83
 },
 {
   "rank": 96,
   "name": "Marvin Jones",
   "position": "WR",
   "positionRank": "WR42",
   "team": "DET",
   "bye": 10,
   "age": "",
   "pts": 47.36,
   "adp": "100",
   "vbd": -0.48
 },
 {
   "rank": 97,
   "name": "Danny Woodhead",
   "position": "RB",
   "positionRank": "RB32",
   "team": "SD",
   "bye": 11,
   "age": "",
   "pts": 49.08,
   "adp": "97",
   "vbd": -0.61
 },
 {
   "rank": 98,
   "name": "Dwayne Allen",
   "position": "TE",
   "positionRank": "TE12",
   "team": "IND",
   "bye": 10,
   "age": "",
   "pts": 36.41,
   "adp": "98",
   "vbd": 0.5
 },
 {
   "rank": 99,
   "name": "Sterling Shepard",
   "position": "WR",
   "positionRank": "WR43",
   "team": "NYG",
   "bye": 8,
   "age": "",
   "pts": 47.04,
   "adp": "103",
   "vbd": -0.8
 },
 {
   "rank": 100,
   "name": "Matthew Stafford",
   "position": "QB",
   "positionRank": "QB13",
   "team": "DET",
   "bye": 10,
   "age": "",
   "pts": 96.88,
   "adp": "104",
   "vbd": -0.75
 },
 {
   "rank": 101,
   "name": "Jason Witten",
   "position": "TE",
   "positionRank": "TE13",
   "team": "DAL",
   "bye": 7,
   "age": "",
   "pts": 35.73,
   "adp": "101",
   "vbd": -0.17
 },
 {
   "rank": 102,
   "name": "Josh Gordon",
   "position": "WR",
   "positionRank": "WR44",
   "team": "CLE",
   "bye": 13,
   "age": "",
   "pts": 46.29,
   "adp": "107",
   "vbd": -1.55
 },
 {
   "rank": 103,
   "name": "T.J. Yeldon",
   "position": "RB",
   "positionRank": "RB33",
   "team": "JAX",
   "bye": 5,
   "age": "",
   "pts": 48.32,
   "adp": "95",
   "vbd": -1.37
 },
 {
   "rank": 104,
   "name": "Dwayne Harris",
   "position": "WR",
   "positionRank": "WR45",
   "team": "NYG",
   "bye": 8,
   "age": "",
   "pts": 46.08,
   "adp": "111",
   "vbd": -1.76
 },
 {
   "rank": 105,
   "name": "Martellus Bennett",
   "position": "TE",
   "positionRank": "TE14",
   "team": "NE",
   "bye": 9,
   "age": "",
   "pts": 35.57,
   "adp": "96",
   "vbd": -0.33
 },
 {
   "rank": 106,
   "name": "Philip Rivers",
   "position": "QB",
   "positionRank": "QB14",
   "team": "SD",
   "bye": 11,
   "age": "",
   "pts": 96.56,
   "adp": "108",
   "vbd": -1.07
 },
 {
   "rank": 107,
   "name": "DeAngelo Williams",
   "position": "RB",
   "positionRank": "RB34",
   "team": "PIT",
   "bye": 8,
   "age": "",
   "pts": 47.89,
   "adp": "105",
   "vbd": -1.8
 },
 {
   "rank": 108,
   "name": "Tevin Coleman",
   "position": "RB",
   "positionRank": "RB35",
   "team": "ATL",
   "bye": 11,
   "age": "",
   "pts": 47.84,
   "adp": "102",
   "vbd": -1.85
 },
 {
   "rank": 109,
   "name": "Torrey Smith",
   "position": "WR",
   "positionRank": "WR46",
   "team": "SF",
   "bye": 8,
   "age": "",
   "pts": 45.34,
   "adp": "112",
   "vbd": -2.5
 },
 {
   "rank": 110,
   "name": "LeGarrette Blount",
   "position": "RB",
   "positionRank": "RB36",
   "team": "NE",
   "bye": 9,
   "age": "",
   "pts": 47.54,
   "adp": "106",
   "vbd": -2.15
 },
 {
   "rank": 111,
   "name": "Kevin White",
   "position": "WR",
   "positionRank": "WR47",
   "team": "CHI",
   "bye": 9,
   "age": "",
   "pts": 44.7,
   "adp": "113",
   "vbd": -3.14
 },
 {
   "rank": 112,
   "name": "Kirk Cousins",
   "position": "QB",
   "positionRank": "QB15",
   "team": "WAS",
   "bye": 9,
   "age": "",
   "pts": 96.08,
   "adp": "122",
   "vbd": -1.55
 },
 {
   "rank": 113,
   "name": "Quan Bray",
   "position": "WR",
   "positionRank": "WR48",
   "team": "IND",
   "bye": 10,
   "age": "",
   "pts": 44.48,
   "adp": "109",
   "vbd": -3.36
 },
 {
   "rank": 114,
   "name": "Marcus Mariota",
   "position": "QB",
   "positionRank": "QB16",
   "team": "TEN",
   "bye": 13,
   "age": "",
   "pts": 95.92,
   "adp": "117",
   "vbd": -1.71
 },
 {
   "rank": 115,
   "name": "Tyler Ervin",
   "position": "RB",
   "positionRank": "RB37",
   "team": "HOU",
   "bye": 9,
   "age": "",
   "pts": 46.4,
   "adp": "115",
   "vbd": -3.29
 },
 {
   "rank": 116,
   "name": "Darren Sproles",
   "position": "RB",
   "positionRank": "RB38",
   "team": "PHI",
   "bye": 4,
   "age": "",
   "pts": 46.2,
   "adp": "114",
   "vbd": -3.49
 },
 {
   "rank": 117,
   "name": "Willie Snead",
   "position": "WR",
   "positionRank": "WR49",
   "team": "NO",
   "bye": 5,
   "age": "",
   "pts": 43.04,
   "adp": "124",
   "vbd": -4.8
 },
 {
   "rank": 118,
   "name": "Stefon Diggs",
   "position": "WR",
   "positionRank": "WR50",
   "team": "MIN",
   "bye": 6,
   "age": "",
   "pts": 42.88,
   "adp": "116",
   "vbd": -4.96
 },
 {
   "rank": 119,
   "name": "DeAndre Washington",
   "position": "RB",
   "positionRank": "RB39",
   "team": "OAK",
   "bye": 10,
   "age": "",
   "pts": 45.76,
   "adp": "127",
   "vbd": -3.93
 },
 {
   "rank": 120,
   "name": "Jay Ajayi",
   "position": "RB",
   "positionRank": "RB39",
   "team": "MIA",
   "bye": 8,
   "age": "",
   "pts": 45.76,
   "adp": "110",
   "vbd": -3.93
 },
 {
   "rank": 121,
   "name": "Vincent Jackson",
   "position": "WR",
   "positionRank": "WR51",
   "team": "TB",
   "bye": 6,
   "age": "",
   "pts": 42.14,
   "adp": "123",
   "vbd": -5.7
 },
 {
   "rank": 122,
   "name": "Ryan Fitzpatrick",
   "position": "QB",
   "positionRank": "QB17",
   "team": "NYJ",
   "bye": 11,
   "age": "",
   "pts": 95.05,
   "adp": "120",
   "vbd": -2.59
 },
 {
   "rank": 123,
   "name": "Andre Ellington",
   "position": "RB",
   "positionRank": "RB41",
   "team": "ARI",
   "bye": 9,
   "age": "",
   "pts": 44.79,
   "adp": "126",
   "vbd": -4.9
 },
 {
   "rank": 124,
   "name": "Charles Sims",
   "position": "RB",
   "positionRank": "RB42",
   "team": "TB",
   "bye": 6,
   "age": "",
   "pts": 44.76,
   "adp": "118",
   "vbd": -4.93
 },
 {
   "rank": 125,
   "name": "Chris Ivory",
   "position": "RB",
   "positionRank": "RB42",
   "team": "JAX",
   "bye": 5,
   "age": "",
   "pts": 44.76,
   "adp": "119",
   "vbd": -4.93
 },
 {
   "rank": 126,
   "name": "Andy Dalton",
   "position": "QB",
   "positionRank": "QB18",
   "team": "CIN",
   "bye": 9,
   "age": "",
   "pts": 94.8,
   "adp": "130",
   "vbd": -2.83
 },
 {
   "rank": 127,
   "name": "Lucky Whitehead",
   "position": "WR",
   "positionRank": "WR52",
   "team": "DAL",
   "bye": 7,
   "age": "",
   "pts": 41.12,
   "adp": "129",
   "vbd": -6.72
 },
 {
   "rank": 128,
   "name": "Eric Ebron",
   "position": "TE",
   "positionRank": "TE15",
   "team": "DET",
   "bye": 10,
   "age": "",
   "pts": 33.89,
   "adp": "121",
   "vbd": -2.01
 },
 {
   "rank": 129,
   "name": "Shane Vereen",
   "position": "RB",
   "positionRank": "RB44",
   "team": "NYG",
   "bye": 8,
   "age": "",
   "pts": 43.96,
   "adp": "125",
   "vbd": -5.73
 },
 {
   "rank": 130,
   "name": "Phillip Dorsett",
   "position": "WR",
   "positionRank": "WR53",
   "team": "IND",
   "bye": 10,
   "age": "",
   "pts": 40.16,
   "adp": "133",
   "vbd": -7.68
 },
 {
   "rank": 131,
   "name": "Devin Funchess",
   "position": "WR",
   "positionRank": "WR53",
   "team": "CAR",
   "bye": 7,
   "age": "",
   "pts": 40.16,
   "adp": "132",
   "vbd": -7.68
 },
 {
   "rank": 132,
   "name": "Ryan Tannehill",
   "position": "QB",
   "positionRank": "QB19",
   "team": "MIA",
   "bye": 8,
   "age": "",
   "pts": 94.24,
   "adp": "135",
   "vbd": -3.39
 },
 {
   "rank": 133,
   "name": "Derek Carr",
   "position": "QB",
   "positionRank": "QB20",
   "team": "OAK",
   "bye": 10,
   "age": "",
   "pts": 93.84,
   "adp": "128",
   "vbd": -3.79
 },
 {
   "rank": 134,
   "name": "Zach Miller",
   "position": "TE",
   "positionRank": "TE16",
   "team": "CHI",
   "bye": 9,
   "age": "",
   "pts": 33.36,
   "adp": "134",
   "vbd": -2.54
 },
 {
   "rank": 135,
   "name": "Jamison Crowder",
   "position": "WR",
   "positionRank": "WR55",
   "team": "WAS",
   "bye": 9,
   "age": "",
   "pts": 38.56,
   "adp": "145",
   "vbd": -9.28
 },
 {
   "rank": 136,
   "name": "Rishard Matthews",
   "position": "WR",
   "positionRank": "WR56",
   "team": "TEN",
   "bye": 13,
   "age": "",
   "pts": 38.4,
   "adp": "141",
   "vbd": -9.44
 },
 {
   "rank": 137,
   "name": "Michael Thomas",
   "position": "WR",
   "positionRank": "WR56",
   "team": "NO",
   "bye": 5,
   "age": "",
   "pts": 38.4,
   "adp": "138",
   "vbd": -9.44
 },
 {
   "rank": 138,
   "name": "Justin Forsett",
   "position": "RB",
   "positionRank": "RB45",
   "team": "BAL",
   "bye": 8,
   "age": "",
   "pts": 42.13,
   "adp": "131",
   "vbd": -7.56
 },
 {
   "rank": 139,
   "name": "Laquon Treadwell",
   "position": "WR",
   "positionRank": "WR58",
   "team": "MIN",
   "bye": 6,
   "age": "",
   "pts": 37.6,
   "adp": "136",
   "vbd": -10.24
 },
 {
   "rank": 140,
   "name": "Robert Woods",
   "position": "WR",
   "positionRank": "WR59",
   "team": "BUF",
   "bye": 10,
   "age": "",
   "pts": 37.18,
   "adp": "147",
   "vbd": -10.66
 },
 {
   "rank": 141,
   "name": "Cordarrelle Patterson",
   "position": "WR",
   "positionRank": "WR60",
   "team": "MIN",
   "bye": 6,
   "age": "",
   "pts": 37.12,
   "adp": "140",
   "vbd": -10.72
 },
 {
   "rank": 142,
   "name": "Jimmy Graham",
   "position": "TE",
   "positionRank": "TE17",
   "team": "SEA",
   "bye": 5,
   "age": "",
   "pts": 32.79,
   "adp": "137",
   "vbd": -3.12
 },
 {
   "rank": 143,
   "name": "Benny Cunningham",
   "position": "RB",
   "positionRank": "RB46",
   "team": "LA",
   "bye": 8,
   "age": "",
   "pts": 41.12,
   "adp": "146",
   "vbd": -8.57
 },
 {
   "rank": 144,
   "name": "Alex Smith",
   "position": "QB",
   "positionRank": "QB21",
   "team": "KC",
   "bye": 5,
   "age": "",
   "pts": 93.04,
   "adp": "148",
   "vbd": -4.59
 },
 {
   "rank": 145,
   "name": "Steve Smith",
   "position": "WR",
   "positionRank": "WR61",
   "team": "BAL",
   "bye": 8,
   "age": "",
   "pts": 36.05,
   "adp": "142",
   "vbd": -11.79
 },
 {
   "rank": 146,
   "name": "James Starks",
   "position": "RB",
   "positionRank": "RB47",
   "team": "GB",
   "bye": 4,
   "age": "",
   "pts": 40.6,
   "adp": "143",
   "vbd": -9.09
 },
 {
   "rank": 147,
   "name": "Bilal Powell",
   "position": "RB",
   "positionRank": "RB48",
   "team": "NYJ",
   "bye": 11,
   "age": "",
   "pts": 40.53,
   "adp": "144",
   "vbd": -9.16
 },
 {
   "rank": 148,
   "name": "Pierre Garcon",
   "position": "WR",
   "positionRank": "WR62",
   "team": "WAS",
   "bye": 9,
   "age": "",
   "pts": 35.9,
   "adp": "150",
   "vbd": -11.94
 },
 {
   "rank": 149,
   "name": "Theo Riddick",
   "position": "RB",
   "positionRank": "RB49",
   "team": "DET",
   "bye": 10,
   "age": "",
   "pts": 40.32,
   "adp": "139",
   "vbd": -9.37
 },
 {
   "rank": 150,
   "name": "Tyreek Hill",
   "position": "WR",
   "positionRank": "WR63",
   "team": "KC",
   "bye": 5,
   "age": "",
   "pts": 35.58,
   "adp": "152",
   "vbd": -12.26
 },
 {
   "rank": 151,
   "name": "Mohamed Sanu",
   "position": "WR",
   "positionRank": "WR64",
   "team": "ATL",
   "bye": 11,
   "age": "",
   "pts": 35.52,
   "adp": "151",
   "vbd": -12.32
 },
 {
   "rank": 152,
   "name": "Derrick Henry",
   "position": "RB",
   "positionRank": "RB50",
   "team": "TEN",
   "bye": 13,
   "age": "",
   "pts": 40,
   "adp": "149",
   "vbd": -9.69
 },
 {
   "rank": 153,
   "name": "Kenny Britt",
   "position": "WR",
   "positionRank": "WR65",
   "team": "LA",
   "bye": 8,
   "age": "",
   "pts": 34.66,
   "adp": "156",
   "vbd": -13.18
 },
 {
   "rank": 154,
   "name": "Terrance Williams",
   "position": "WR",
   "positionRank": "WR66",
   "team": "DAL",
   "bye": 7,
   "age": "",
   "pts": 34.62,
   "adp": "155",
   "vbd": -13.22
 },
 {
   "rank": 155,
   "name": "Jared Cook",
   "position": "TE",
   "positionRank": "TE18",
   "team": "GB",
   "bye": 4,
   "age": "",
   "pts": 32.05,
   "adp": "160",
   "vbd": -3.85
 },
 {
   "rank": 156,
   "name": "Danny Amendola",
   "position": "WR",
   "positionRank": "WR67",
   "team": "NE",
   "bye": 9,
   "age": "",
   "pts": 34.12,
   "adp": "153",
   "vbd": -13.72
 },
 {
   "rank": 157,
   "name": "Tyler Boyd",
   "position": "WR",
   "positionRank": "WR68",
   "team": "CIN",
   "bye": 9,
   "age": "",
   "pts": 33.76,
   "adp": "157",
   "vbd": -14.08
 },
 {
   "rank": 158,
   "name": "Kamar Aiken",
   "position": "WR",
   "positionRank": "WR69",
   "team": "BAL",
   "bye": 8,
   "age": "",
   "pts": 33.44,
   "adp": "154",
   "vbd": -14.4
 },
 {
   "rank": 159,
   "name": "Jermaine Kearse",
   "position": "WR",
   "positionRank": "WR70",
   "team": "SEA",
   "bye": 5,
   "age": "",
   "pts": 32.86,
   "adp": "159",
   "vbd": -14.98
 },
 {
   "rank": 160,
   "name": "Tajae Sharpe",
   "position": "WR",
   "positionRank": "WR71",
   "team": "TEN",
   "bye": 13,
   "age": "",
   "pts": 31.1,
   "adp": "163",
   "vbd": -16.74
 },
 {
   "rank": 161,
   "name": "Dorial Green-Beckham",
   "position": "WR",
   "positionRank": "WR72",
   "team": "PHI",
   "bye": 4,
   "age": "",
   "pts": 30.78,
   "adp": "164",
   "vbd": -17.06
 },
 {
   "rank": 162,
   "name": "Kenny Stills",
   "position": "WR",
   "positionRank": "WR73",
   "team": "MIA",
   "bye": 8,
   "age": "",
   "pts": 30.46,
   "adp": "161",
   "vbd": -17.38
 },
 {
   "rank": 163,
   "name": "Will Fuller",
   "position": "WR",
   "positionRank": "WR74",
   "team": "HOU",
   "bye": 9,
   "age": "",
   "pts": 30.4,
   "adp": "162",
   "vbd": -17.44
 },
 {
   "rank": 164,
   "name": "Charles Clay",
   "position": "TE",
   "positionRank": "TE19",
   "team": "BUF",
   "bye": 10,
   "age": "",
   "pts": 30.8,
   "adp": "165",
   "vbd": -5.1
 },
 {
   "rank": 165,
   "name": "Anquan Boldin",
   "position": "WR",
   "positionRank": "WR75",
   "team": "DET",
   "bye": 10,
   "age": "",
   "pts": 30.02,
   "adp": "167",
   "vbd": -17.82
 },
 {
   "rank": 166,
   "name": "Mike Wallace",
   "position": "WR",
   "positionRank": "WR76",
   "team": "BAL",
   "bye": 8,
   "age": "",
   "pts": 29.34,
   "adp": "170",
   "vbd": -18.5
 },
 {
   "rank": 167,
   "name": "Devontae Booker",
   "position": "RB",
   "positionRank": "RB51",
   "team": "DEN",
   "bye": 11,
   "age": "",
   "pts": 35.09,
   "adp": "169",
   "vbd": -14.6
 },
 {
   "rank": 168,
   "name": "Josh Huff",
   "position": "WR",
   "positionRank": "WR77",
   "team": "PHI",
   "bye": 4,
   "age": "",
   "pts": 28.8,
   "adp": "172",
   "vbd": -19.04
 },
 {
   "rank": 169,
   "name": "Will Tye",
   "position": "TE",
   "positionRank": "TE20",
   "team": "NYG",
   "bye": 8,
   "age": "",
   "pts": 30.24,
   "adp": "166",
   "vbd": -5.66
 },
 {
   "rank": 170,
   "name": "Quinton Patton",
   "position": "WR",
   "positionRank": "WR78",
   "team": "SF",
   "bye": 8,
   "age": "",
   "pts": 28.32,
   "adp": "n/a",
   "vbd": -19.52
 },
 {
   "rank": 171,
   "name": "Chris Hogan",
   "position": "WR",
   "positionRank": "WR79",
   "team": "NE",
   "bye": 9,
   "age": "",
   "pts": 28.16,
   "adp": "168",
   "vbd": -19.68
 },
 {
   "rank": 172,
   "name": "Jordan Norwood",
   "position": "WR",
   "positionRank": "WR80",
   "team": "DEN",
   "bye": 11,
   "age": "",
   "pts": 27.68,
   "adp": "175",
   "vbd": -20.16
 },
 {
   "rank": 173,
   "name": "Kyle Rudolph",
   "position": "TE",
   "positionRank": "TE21",
   "team": "MIN",
   "bye": 6,
   "age": "",
   "pts": 30,
   "adp": "174",
   "vbd": -5.9
 },
 {
   "rank": 174,
   "name": "J.J. Nelson",
   "position": "WR",
   "positionRank": "WR81",
   "team": "ARI",
   "bye": 9,
   "age": "",
   "pts": 26.88,
   "adp": "n/a",
   "vbd": -20.96
 },
 {
   "rank": 175,
   "name": "Breshad Perriman",
   "position": "WR",
   "positionRank": "WR82",
   "team": "BAL",
   "bye": 8,
   "age": "",
   "pts": 26.55,
   "adp": "n/a",
   "vbd": -21.29
 },
 {
   "rank": 176,
   "name": "Terrance West",
   "position": "RB",
   "positionRank": "RB52",
   "team": "BAL",
   "bye": 8,
   "age": "",
   "pts": 32.21,
   "adp": "171",
   "vbd": -17.48
 },
 {
   "rank": 177,
   "name": "Kenneth Dixon",
   "position": "RB",
   "positionRank": "RB53",
   "team": "BAL",
   "bye": 8,
   "age": "",
   "pts": 32.18,
   "adp": "176",
   "vbd": -17.52
 },
 {
   "rank": 178,
   "name": "Clive Walford",
   "position": "TE",
   "positionRank": "TE22",
   "team": "OAK",
   "bye": 10,
   "age": "",
   "pts": 28.96,
   "adp": "178",
   "vbd": -6.94
 },
 {
   "rank": 179,
   "name": "Reggie Bush",
   "position": "RB",
   "positionRank": "RB54",
   "team": "BUF",
   "bye": 10,
   "age": "",
   "pts": 31.52,
   "adp": "179",
   "vbd": -18.17
 },
 {
   "rank": 180,
   "name": "James White",
   "position": "RB",
   "positionRank": "RB55",
   "team": "NE",
   "bye": 9,
   "age": "",
   "pts": 31.48,
   "adp": "173",
   "vbd": -18.21
 },
 {
   "rank": 181,
   "name": "Dwayne Washington",
   "position": "RB",
   "positionRank": "RB56",
   "team": "DET",
   "bye": 10,
   "age": "",
   "pts": 31.36,
   "adp": "181",
   "vbd": -18.33
 },
 {
   "rank": 182,
   "name": "Chris Thompson",
   "position": "RB",
   "positionRank": "RB57",
   "team": "WAS",
   "bye": 9,
   "age": "",
   "pts": 31.32,
   "adp": "180",
   "vbd": -18.37
 },
 {
   "rank": 183,
   "name": "Spencer Ware",
   "position": "RB",
   "positionRank": "RB57",
   "team": "KC",
   "bye": 5,
   "age": "",
   "pts": 31.32,
   "adp": "177",
   "vbd": -18.37
 },
 {
   "rank": 184,
   "name": "Jerick McKinnon",
   "position": "RB",
   "positionRank": "RB59",
   "team": "MIN",
   "bye": 6,
   "age": "",
   "pts": 30.56,
   "adp": "184",
   "vbd": -19.13
 },
 {
   "rank": 185,
   "name": "Dion Lewis",
   "position": "RB",
   "positionRank": "RB60",
   "team": "NE",
   "bye": 9,
   "age": "",
   "pts": 30.04,
   "adp": "183",
   "vbd": -19.65
 },
 {
   "rank": 186,
   "name": "Shaun Draughn",
   "position": "RB",
   "positionRank": "RB61",
   "team": "SF",
   "bye": 8,
   "age": "",
   "pts": 29.81,
   "adp": "187",
   "vbd": -19.88
 },
 {
   "rank": 187,
   "name": "Dexter McCluster",
   "position": "RB",
   "positionRank": "RB62",
   "team": "TEN",
   "bye": 13,
   "age": "",
   "pts": 29.72,
   "adp": "182",
   "vbd": -19.97
 },
 {
   "rank": 188,
   "name": "Matt Ryan",
   "position": "QB",
   "positionRank": "QB22",
   "team": "ATL",
   "bye": 11,
   "age": "",
   "pts": 85.84,
   "adp": "204",
   "vbd": -11.79
 },
 {
   "rank": 189,
   "name": "Vance McDonald",
   "position": "TE",
   "positionRank": "TE23",
   "team": "SF",
   "bye": 8,
   "age": "",
   "pts": 26.96,
   "adp": "n/a",
   "vbd": -8.94
 },
 {
   "rank": 190,
   "name": "Austin Seferian-Jenkins",
   "position": "TE",
   "positionRank": "TE24",
   "team": "TB",
   "bye": 6,
   "age": "",
   "pts": 26.49,
   "adp": "205",
   "vbd": -9.42
 },
 {
   "rank": 191,
   "name": "Jay Cutler",
   "position": "QB",
   "positionRank": "QB23",
   "team": "CHI",
   "bye": 9,
   "age": "",
   "pts": 84.91,
   "adp": "214",
   "vbd": -12.73
 },
 {
   "rank": 192,
   "name": "Blaine Gabbert",
   "position": "QB",
   "positionRank": "QB24",
   "team": "SF",
   "bye": 8,
   "age": "",
   "pts": 82.46,
   "adp": "n/a",
   "vbd": -15.17
 },
 {
   "rank": 193,
   "name": "Minnesota Vikings DEF",
   "position": "D",
   "positionRank": "TD1",
   "team": "MIN",
   "bye": 6,
   "age": "",
   "pts": 106.88,
   "adp": "197",
   "vbd": 11.73
 },
 {
   "rank": 193,
   "name": "Minnesota Vikings ST",
   "position": "ST",
   "positionRank": "TD1",
   "team": "MIN",
   "bye": 6,
   "age": "",
   "pts": 106.88,
   "adp": "197",
   "vbd": 11.73
 },
 {
   "rank": 194,
   "name": "Carolina Panthers DEF",
   "position": "D",
   "positionRank": "TD2",
   "team": "CAR",
   "bye": 7,
   "age": "",
   "pts": 105.76,
   "adp": "185",
   "vbd": 10.61
 },
 {
   "rank": 194,
   "name": "Carolina Panthers ST",
   "position": "ST",
   "positionRank": "TD2",
   "team": "CAR",
   "bye": 7,
   "age": "",
   "pts": 105.76,
   "adp": "185",
   "vbd": 10.61
 },
 {
   "rank": 195,
   "name": "Kansas City Chiefs DEF",
   "position": "D",
   "positionRank": "TD3",
   "team": "KC",
   "bye": 5,
   "age": "",
   "pts": 104.8,
   "adp": "193",
   "vbd": 9.65
 },
 {
   "rank": 195,
   "name": "Kansas City Chiefs ST",
   "position": "ST",
   "positionRank": "TD3",
   "team": "KC",
   "bye": 5,
   "age": "",
   "pts": 104.8,
   "adp": "193",
   "vbd": 9.65
 },
 {
   "rank": 196,
   "name": "Stephen Gostkowski",
   "position": "K",
   "positionRank": "PK1",
   "team": "NE",
   "bye": 9,
   "age": "",
   "pts": 47.68,
   "adp": "189",
   "vbd": 6.51
 },
 {
   "rank": 197,
   "name": "Denver Broncos DEF",
   "position": "D",
   "positionRank": "TD4",
   "team": "DEN",
   "bye": 11,
   "age": "",
   "pts": 103.68,
   "adp": "186",
   "vbd": 8.53
 },
 {
   "rank": 197,
   "name": "Denver Broncos ST",
   "position": "ST",
   "positionRank": "TD4",
   "team": "DEN",
   "bye": 11,
   "age": "",
   "pts": 103.68,
   "adp": "186",
   "vbd": 8.53
 },
 {
   "rank": 198,
   "name": "Graham Gano",
   "position": "K",
   "positionRank": "PK2",
   "team": "CAR",
   "bye": 7,
   "age": "",
   "pts": 46.88,
   "adp": "202",
   "vbd": 5.71
 },
 {
   "rank": 199,
   "name": "Arizona Cardinals DEF",
   "position": "D",
   "positionRank": "TD5",
   "team": "ARI",
   "bye": 9,
   "age": "",
   "pts": 102.4,
   "adp": "191",
   "vbd": 7.25
 },
 {
   "rank": 199,
   "name": "Arizona Cardinals ST",
   "position": "ST",
   "positionRank": "TD5",
   "team": "ARI",
   "bye": 9,
   "age": "",
   "pts": 102.4,
   "adp": "191",
   "vbd": 7.25
 },
 {
   "rank": 200,
   "name": "Seattle Seahawks DEF",
   "position": "D",
   "positionRank": "TD5",
   "team": "SEA",
   "bye": 5,
   "age": "",
   "pts": 102.4,
   "adp": "188",
   "vbd": 7.25
 },
 {
   "rank": 200,
   "name": "Seattle Seahawks ST",
   "position": "ST",
   "positionRank": "TD5",
   "team": "SEA",
   "bye": 5,
   "age": "",
   "pts": 102.4,
   "adp": "188",
   "vbd": 7.25
 },
 {
   "rank": 201,
   "name": "Mason Crosby",
   "position": "K",
   "positionRank": "PK3",
   "team": "GB",
   "bye": 4,
   "age": "",
   "pts": 45.6,
   "adp": "201",
   "vbd": 4.43
 },
 {
   "rank": 202,
   "name": "Chris Boswell",
   "position": "K",
   "positionRank": "PK4",
   "team": "PIT",
   "bye": 8,
   "age": "",
   "pts": 45.44,
   "adp": "203",
   "vbd": 4.27
 },
 {
   "rank": 203,
   "name": "Steve Hauschka",
   "position": "K",
   "positionRank": "PK5",
   "team": "SEA",
   "bye": 5,
   "age": "",
   "pts": 44.96,
   "adp": "194",
   "vbd": 3.79
 },
 {
   "rank": 204,
   "name": "Chandler Catanzaro",
   "position": "K",
   "positionRank": "PK5",
   "team": "ARI",
   "bye": 9,
   "age": "",
   "pts": 44.96,
   "adp": "208",
   "vbd": 3.79
 },
 {
   "rank": 205,
   "name": "Blair Walsh",
   "position": "K",
   "positionRank": "PK7",
   "team": "MIN",
   "bye": 6,
   "age": "",
   "pts": 43.52,
   "adp": "211",
   "vbd": 2.35
 },
 {
   "rank": 206,
   "name": "Josh Brown",
   "position": "K",
   "positionRank": "PK8",
   "team": "NYG",
   "bye": 8,
   "age": "",
   "pts": 43.49,
   "adp": "216",
   "vbd": 2.31
 },
 {
   "rank": 207,
   "name": "Pittsburgh Steelers DEF",
   "position": "D",
   "positionRank": "TD7",
   "team": "PIT",
   "bye": 8,
   "age": "",
   "pts": 99.36,
   "adp": "210",
   "vbd": 4.21
 },
 {
   "rank": 207,
   "name": "Pittsburgh Steelers ST",
   "position": "ST",
   "positionRank": "TD7",
   "team": "PIT",
   "bye": 8,
   "age": "",
   "pts": 99.36,
   "adp": "210",
   "vbd": 4.21
 },
 {
   "rank": 208,
   "name": "Pharoh Cooper",
   "position": "WR",
   "positionRank": "WR83",
   "team": "LA",
   "bye": 8,
   "age": "",
   "pts": 26.42,
   "adp": "n/a",
   "vbd": -21.42
 },
 {
   "rank": 209,
   "name": "Justin Tucker",
   "position": "K",
   "positionRank": "PK9",
   "team": "BAL",
   "bye": 8,
   "age": "",
   "pts": 42.4,
   "adp": "200",
   "vbd": 1.23
 },
 {
   "rank": 210,
   "name": "Cairo Santos",
   "position": "K",
   "positionRank": "PK10",
   "team": "KC",
   "bye": 5,
   "age": "",
   "pts": 42.24,
   "adp": "213",
   "vbd": 1.07
 },
 {
   "rank": 211,
   "name": "Los Angeles Rams DEF",
   "position": "D",
   "positionRank": "TD8",
   "team": "LA",
   "bye": 8,
   "age": "",
   "pts": 98.72,
   "adp": "196",
   "vbd": 3.57
 },
 {
   "rank": 211,
   "name": "Los Angeles Rams ST",
   "position": "ST",
   "positionRank": "TD8",
   "team": "LA",
   "bye": 8,
   "age": "",
   "pts": 98.72,
   "adp": "196",
   "vbd": 3.57
 },
 {
   "rank": 212,
   "name": "New England Patriots DEF",
   "position": "D",
   "positionRank": "TD8",
   "team": "NE",
   "bye": 9,
   "age": "",
   "pts": 98.72,
   "adp": "198",
   "vbd": 3.57
 },
 {
   "rank": 212,
   "name": "New England Patriots ST",
   "position": "ST",
   "positionRank": "TD8",
   "team": "NE",
   "bye": 9,
   "age": "",
   "pts": 98.72,
   "adp": "198",
   "vbd": 3.57
 },
 {
   "rank": 213,
   "name": "Brandon McManus",
   "position": "K",
   "positionRank": "PK11",
   "team": "DEN",
   "bye": 11,
   "age": "",
   "pts": 41.76,
   "adp": "207",
   "vbd": 0.59
 },
 {
   "rank": 214,
   "name": "Dan Bailey",
   "position": "K",
   "positionRank": "PK12",
   "team": "DAL",
   "bye": 7,
   "age": "",
   "pts": 41.6,
   "adp": "209",
   "vbd": 0.43
 },
 {
   "rank": 215,
   "name": "Philadelphia Eagles DEF",
   "position": "D",
   "positionRank": "TD10",
   "team": "PHI",
   "bye": 4,
   "age": "",
   "pts": 97.92,
   "adp": "212",
   "vbd": 2.77
 },
 {
   "rank": 215,
   "name": "Philadelphia Eagles ST",
   "position": "ST",
   "positionRank": "TD10",
   "team": "PHI",
   "bye": 4,
   "age": "",
   "pts": 97.92,
   "adp": "212",
   "vbd": 2.77
 },
 {
   "rank": 216,
   "name": "Cincinnati Bengals DEF",
   "position": "D",
   "positionRank": "TD10",
   "team": "CIN",
   "bye": 9,
   "age": "",
   "pts": 97.92,
   "adp": "199",
   "vbd": 2.77
 },
 {
   "rank": 216,
   "name": "Cincinnati Bengals ST",
   "position": "ST",
   "positionRank": "TD10",
   "team": "CIN",
   "bye": 9,
   "age": "",
   "pts": 97.92,
   "adp": "199",
   "vbd": 2.77
 },
 {
   "rank": 217,
   "name": "Adam Humphries",
   "position": "WR",
   "positionRank": "WR84",
   "team": "TB",
   "bye": 6,
   "age": "",
   "pts": 25.92,
   "adp": "n/a",
   "vbd": -21.92
 },
 {
   "rank": 218,
   "name": "Bruce Ellington",
   "position": "WR",
   "positionRank": "WR85",
   "team": "SF",
   "bye": 8,
   "age": "",
   "pts": 25.57,
   "adp": "158",
   "vbd": -22.27
 },
 {
   "rank": 219,
   "name": "Green Bay Packers DEF",
   "position": "D",
   "positionRank": "TD12",
   "team": "GB",
   "bye": 4,
   "age": "",
   "pts": 95.68,
   "adp": "206",
   "vbd": 0.53
 },
 {
   "rank": 219,
   "name": "Green Bay Packers ST",
   "position": "ST",
   "positionRank": "TD12",
   "team": "GB",
   "bye": 4,
   "age": "",
   "pts": 95.68,
   "adp": "206",
   "vbd": 0.53
 },
 {
   "rank": 220,
   "name": "Seth Roberts",
   "position": "WR",
   "positionRank": "WR86",
   "team": "OAK",
   "bye": 10,
   "age": "",
   "pts": 25.44,
   "adp": "n/a",
   "vbd": -22.4
 },
 {
   "rank": 221,
   "name": "Jared Abbrederis",
   "position": "WR",
   "positionRank": "WR87",
   "team": "GB",
   "bye": 4,
   "age": "",
   "pts": 23.68,
   "adp": "n/a",
   "vbd": -24.16
 },
 {
   "rank": 222,
   "name": "Josh Doctson",
   "position": "WR",
   "positionRank": "WR88",
   "team": "WAS",
   "bye": 9,
   "age": "",
   "pts": 23.66,
   "adp": "n/a",
   "vbd": -24.18
 },
 {
   "rank": 223,
   "name": "Kendall Wright",
   "position": "WR",
   "positionRank": "WR89",
   "team": "TEN",
   "bye": 13,
   "age": "",
   "pts": 23.53,
   "adp": "n/a",
   "vbd": -24.31
 },
 {
   "rank": 224,
   "name": "Marc Mariani",
   "position": "WR",
   "positionRank": "WR90",
   "team": "CHI",
   "bye": 9,
   "age": "",
   "pts": 23.45,
   "adp": "n/a",
   "vbd": -24.39
 },
 {
   "rank": 225,
   "name": "Nelson Agholor",
   "position": "WR",
   "positionRank": "WR91",
   "team": "PHI",
   "bye": 4,
   "age": "",
   "pts": 22.88,
   "adp": "n/a",
   "vbd": -24.96
 },
 {
   "rank": 226,
   "name": "T.J. Jones",
   "position": "WR",
   "positionRank": "WR92",
   "team": "DET",
   "bye": 10,
   "age": "",
   "pts": 22.24,
   "adp": "n/a",
   "vbd": -25.6
 },
 {
   "rank": 227,
   "name": "Kenjon Barner",
   "position": "RB",
   "positionRank": "RB63",
   "team": "PHI",
   "bye": 4,
   "age": "",
   "pts": 28.76,
   "adp": "190",
   "vbd": -20.93
 },
 {
   "rank": 228,
   "name": "Jaelen Strong",
   "position": "WR",
   "positionRank": "WR93",
   "team": "HOU",
   "bye": 9,
   "age": "",
   "pts": 22.21,
   "adp": "n/a",
   "vbd": -25.63
 },
 {
   "rank": 229,
   "name": "Travaris Cadet",
   "position": "RB",
   "positionRank": "RB64",
   "team": "NO",
   "bye": 5,
   "age": "",
   "pts": 27.62,
   "adp": "195",
   "vbd": -22.07
 },
 {
   "rank": 230,
   "name": "Rashad Greene",
   "position": "WR",
   "positionRank": "WR94",
   "team": "JAX",
   "bye": 5,
   "age": "",
   "pts": 22.08,
   "adp": "n/a",
   "vbd": -25.76
 },
 {
   "rank": 231,
   "name": "Tim Hightower",
   "position": "RB",
   "positionRank": "RB65",
   "team": "NO",
   "bye": 5,
   "age": "",
   "pts": 27.46,
   "adp": "n/a",
   "vbd": -22.24
 },
 {
   "rank": 232,
   "name": "Terrelle Pryor",
   "position": "WR",
   "positionRank": "WR95",
   "team": "CLE",
   "bye": 13,
   "age": "",
   "pts": 21.76,
   "adp": "n/a",
   "vbd": -26.08
 },
 {
   "rank": 233,
   "name": "Christine Michael",
   "position": "RB",
   "positionRank": "RB66",
   "team": "SEA",
   "bye": 5,
   "age": "",
   "pts": 26.47,
   "adp": "n/a",
   "vbd": -23.22
 },
 {
   "rank": 234,
   "name": "Cole Beasley",
   "position": "WR",
   "positionRank": "WR96",
   "team": "DAL",
   "bye": 7,
   "age": "",
   "pts": 21.74,
   "adp": "n/a",
   "vbd": -26.1
 },
 {
   "rank": 235,
   "name": "Chris Johnson",
   "position": "RB",
   "positionRank": "RB67",
   "team": "ARI",
   "bye": 9,
   "age": "",
   "pts": 25.3,
   "adp": "n/a",
   "vbd": -24.39
 },
 {
   "rank": 236,
   "name": "Brandon LaFell",
   "position": "WR",
   "positionRank": "WR97",
   "team": "CIN",
   "bye": 9,
   "age": "",
   "pts": 21.5,
   "adp": "n/a",
   "vbd": -26.34
 },
 {
   "rank": 237,
   "name": "Jordan Howard",
   "position": "RB",
   "positionRank": "RB68",
   "team": "CHI",
   "bye": 9,
   "age": "",
   "pts": 24.96,
   "adp": "n/a",
   "vbd": -24.73
 },
 {
   "rank": 238,
   "name": "Chris Conley",
   "position": "WR",
   "positionRank": "WR98",
   "team": "KC",
   "bye": 5,
   "age": "",
   "pts": 21.28,
   "adp": "n/a",
   "vbd": -26.56
 },
 {
   "rank": 239,
   "name": "C.J. Spiller",
   "position": "RB",
   "positionRank": "RB69",
   "team": "NO",
   "bye": 5,
   "age": "",
   "pts": 24.84,
   "adp": "n/a",
   "vbd": -24.86
 },
 {
   "rank": 240,
   "name": "Tyrell Williams",
   "position": "WR",
   "positionRank": "WR99",
   "team": "SD",
   "bye": 11,
   "age": "",
   "pts": 20.92,
   "adp": "n/a",
   "vbd": -26.92
 },
 {
   "rank": 241,
   "name": "Javorius Allen",
   "position": "RB",
   "positionRank": "RB70",
   "team": "BAL",
   "bye": 8,
   "age": "",
   "pts": 23.36,
   "adp": "n/a",
   "vbd": -26.33
 },
 {
   "rank": 242,
   "name": "Marqise Lee",
   "position": "WR",
   "positionRank": "WR100",
   "team": "JAX",
   "bye": 5,
   "age": "",
   "pts": 20,
   "adp": "n/a",
   "vbd": -27.84
 },
 {
   "rank": 243,
   "name": "Paul Perkins",
   "position": "RB",
   "positionRank": "RB71",
   "team": "NYG",
   "bye": 8,
   "age": "",
   "pts": 23.2,
   "adp": "n/a",
   "vbd": -26.49
 },
 {
   "rank": 244,
   "name": "Jeremy Kerley",
   "position": "WR",
   "positionRank": "WR101",
   "team": "SF",
   "bye": 8,
   "age": "",
   "pts": 19.94,
   "adp": "n/a",
   "vbd": -27.9
 },
 {
   "rank": 245,
   "name": "Darren McFadden",
   "position": "RB",
   "positionRank": "RB72",
   "team": "DAL",
   "bye": 7,
   "age": "",
   "pts": 21.85,
   "adp": "n/a",
   "vbd": -27.84
 },
 {
   "rank": 246,
   "name": "Braxton Miller",
   "position": "WR",
   "positionRank": "WR102",
   "team": "HOU",
   "bye": 9,
   "age": "",
   "pts": 19.84,
   "adp": "n/a",
   "vbd": -28
 },
 {
   "rank": 247,
   "name": "Tyler Gaffney",
   "position": "RB",
   "positionRank": "RB73",
   "team": "NE",
   "bye": 9,
   "age": "",
   "pts": 20.84,
   "adp": "n/a",
   "vbd": -28.86
 },
 {
   "rank": 248,
   "name": "Paul Richardson",
   "position": "WR",
   "positionRank": "WR103",
   "team": "SEA",
   "bye": 5,
   "age": "",
   "pts": 19.7,
   "adp": "n/a",
   "vbd": -28.14
 },
 {
   "rank": 249,
   "name": "Mike Tolbert",
   "position": "RB",
   "positionRank": "RB74",
   "team": "CAR",
   "bye": 7,
   "age": "",
   "pts": 20.8,
   "adp": "n/a",
   "vbd": -28.89
 },
 {
   "rank": 250,
   "name": "Justin Hardy",
   "position": "WR",
   "positionRank": "WR104",
   "team": "ATL",
   "bye": 11,
   "age": "",
   "pts": 18.72,
   "adp": "n/a",
   "vbd": -29.12
 },
 {
   "rank": 251,
   "name": "Jonathan Williams",
   "position": "RB",
   "positionRank": "RB75",
   "team": "BUF",
   "bye": 10,
   "age": "",
   "pts": 20.67,
   "adp": "n/a",
   "vbd": -29.02
 },
 {
   "rank": 252,
   "name": "Brandon Tate",
   "position": "WR",
   "positionRank": "WR105",
   "team": "CIN",
   "bye": 9,
   "age": "",
   "pts": 18.4,
   "adp": "n/a",
   "vbd": -29.44
 },
 {
   "rank": 253,
   "name": "Sammie Coates",
   "position": "WR",
   "positionRank": "WR105",
   "team": "PIT",
   "bye": 8,
   "age": "",
   "pts": 18.4,
   "adp": "n/a",
   "vbd": -29.44
 },
 {
   "rank": 254,
   "name": "C.J. Prosise",
   "position": "RB",
   "positionRank": "RB76",
   "team": "SEA",
   "bye": 5,
   "age": "",
   "pts": 18.88,
   "adp": "n/a",
   "vbd": -30.81
 },
 {
   "rank": 255,
   "name": "Alfred Morris",
   "position": "RB",
   "positionRank": "RB77",
   "team": "DAL",
   "bye": 7,
   "age": "",
   "pts": 18.84,
   "adp": "n/a",
   "vbd": -30.86
 },
 {
   "rank": 256,
   "name": "Charles Johnson",
   "position": "WR",
   "positionRank": "WR107",
   "team": "MIN",
   "bye": 6,
   "age": "",
   "pts": 16.96,
   "adp": "n/a",
   "vbd": -30.88
 },
 {
   "rank": 257,
   "name": "Robert Turbin",
   "position": "RB",
   "positionRank": "RB78",
   "team": "IND",
   "bye": 10,
   "age": "",
   "pts": 18.79,
   "adp": "n/a",
   "vbd": -30.9
 },
 {
   "rank": 258,
   "name": "Daniel Braverman",
   "position": "WR",
   "positionRank": "WR107",
   "team": "CHI",
   "bye": 9,
   "age": "",
   "pts": 16.96,
   "adp": "n/a",
   "vbd": -30.88
 },
 {
   "rank": 259,
   "name": "Khiry Robinson",
   "position": "RB",
   "positionRank": "RB79",
   "team": "NYJ",
   "bye": 11,
   "age": "",
   "pts": 18.17,
   "adp": "n/a",
   "vbd": -31.52
 },
 {
   "rank": 260,
   "name": "Jeff Janis",
   "position": "WR",
   "positionRank": "WR109",
   "team": "GB",
   "bye": 4,
   "age": "",
   "pts": 16.84,
   "adp": "n/a",
   "vbd": -31
 },
 {
   "rank": 261,
   "name": "Cameron Artis-Payne",
   "position": "RB",
   "positionRank": "RB80",
   "team": "CAR",
   "bye": 7,
   "age": "",
   "pts": 17.92,
   "adp": "n/a",
   "vbd": -31.77
 },
 {
   "rank": 262,
   "name": "Brandon Coleman",
   "position": "WR",
   "positionRank": "WR110",
   "team": "NO",
   "bye": 5,
   "age": "",
   "pts": 16.48,
   "adp": "n/a",
   "vbd": -31.36
 },
 {
   "rank": 263,
   "name": "Charcandrick West",
   "position": "RB",
   "positionRank": "RB81",
   "team": "KC",
   "bye": 5,
   "age": "",
   "pts": 17.81,
   "adp": "n/a",
   "vbd": -31.88
 },
 {
   "rank": 264,
   "name": "Mike Thomas",
   "position": "WR",
   "positionRank": "WR111",
   "team": "LA",
   "bye": 8,
   "age": "",
   "pts": 16.16,
   "adp": "n/a",
   "vbd": -31.68
 },
 {
   "rank": 265,
   "name": "Joe Flacco",
   "position": "QB",
   "positionRank": "QB25",
   "team": "BAL",
   "bye": 8,
   "age": "",
   "pts": 81.84,
   "adp": "n/a",
   "vbd": -15.79
 },
 {
   "rank": 266,
   "name": "KaDeem Carey",
   "position": "RB",
   "positionRank": "RB82",
   "team": "CHI",
   "bye": 9,
   "age": "",
   "pts": 17.44,
   "adp": "n/a",
   "vbd": -32.25
 },
 {
   "rank": 267,
   "name": "Quincy Enunwa",
   "position": "WR",
   "positionRank": "WR112",
   "team": "NYJ",
   "bye": 11,
   "age": "",
   "pts": 15.84,
   "adp": "n/a",
   "vbd": -32
 },
 {
   "rank": 268,
   "name": "Virgil Green",
   "position": "TE",
   "positionRank": "TE25",
   "team": "DEN",
   "bye": 11,
   "age": "",
   "pts": 26.4,
   "adp": "192",
   "vbd": -9.5
 },
 {
   "rank": 269,
   "name": "Brock Osweiler",
   "position": "QB",
   "positionRank": "QB26",
   "team": "HOU",
   "bye": 9,
   "age": "",
   "pts": 80.08,
   "adp": "n/a",
   "vbd": -17.55
 },
 {
   "rank": 270,
   "name": "Rob Kelley",
   "position": "RB",
   "positionRank": "RB83",
   "team": "WAS",
   "bye": 9,
   "age": "",
   "pts": 17,
   "adp": "n/a",
   "vbd": -32.69
 },
 {
   "rank": 271,
   "name": "Leonte Carroo",
   "position": "WR",
   "positionRank": "WR113",
   "team": "MIA",
   "bye": 8,
   "age": "",
   "pts": 15.52,
   "adp": "n/a",
   "vbd": -32.32
 },
 {
   "rank": 272,
   "name": "Jordan Cameron",
   "position": "TE",
   "positionRank": "TE26",
   "team": "MIA",
   "bye": 8,
   "age": "",
   "pts": 25.3,
   "adp": "n/a",
   "vbd": -10.6
 },
 {
   "rank": 273,
   "name": "Robert Griffin III",
   "position": "QB",
   "positionRank": "QB27",
   "team": "CLE",
   "bye": 13,
   "age": "",
   "pts": 79.19,
   "adp": "215",
   "vbd": -18.44
 },
 {
   "rank": 274,
   "name": "Zach Zenner",
   "position": "RB",
   "positionRank": "RB84",
   "team": "DET",
   "bye": 10,
   "age": "",
   "pts": 17,
   "adp": "n/a",
   "vbd": -32.7
 },
 {
   "rank": 275,
   "name": "Rashad Ross",
   "position": "WR",
   "positionRank": "WR114",
   "team": "WAS",
   "bye": 9,
   "age": "",
   "pts": 15.12,
   "adp": "n/a",
   "vbd": -32.72
 },
 {
   "rank": 276,
   "name": "Hunter Henry",
   "position": "TE",
   "positionRank": "TE27",
   "team": "SD",
   "bye": 11,
   "age": "",
   "pts": 24.93,
   "adp": "n/a",
   "vbd": -10.97
 },
 {
   "rank": 277,
   "name": "Teddy Bridgewater",
   "position": "QB",
   "positionRank": "QB28",
   "team": "MIN",
   "bye": 6,
   "age": "",
   "pts": 72.39,
   "adp": "n/a",
   "vbd": -25.24
 },
 {
   "rank": 278,
   "name": "Alfred Blue",
   "position": "RB",
   "positionRank": "RB85",
   "team": "HOU",
   "bye": 9,
   "age": "",
   "pts": 16.67,
   "adp": "n/a",
   "vbd": -33.02
 },
 {
   "rank": 279,
   "name": "Davante Adams",
   "position": "WR",
   "positionRank": "WR115",
   "team": "GB",
   "bye": 4,
   "age": "",
   "pts": 14.88,
   "adp": "n/a",
   "vbd": -32.96
 },
 {
   "rank": 280,
   "name": "Jacob Tamme",
   "position": "TE",
   "positionRank": "TE28",
   "team": "ATL",
   "bye": 11,
   "age": "",
   "pts": 24.35,
   "adp": "n/a",
   "vbd": -11.55
 },
 {
   "rank": 281,
   "name": "Taiwan Jones",
   "position": "RB",
   "positionRank": "RB86",
   "team": "OAK",
   "bye": 10,
   "age": "",
   "pts": 16.51,
   "adp": "n/a",
   "vbd": -33.19
 },
 {
   "rank": 282,
   "name": "Eddie Royal",
   "position": "WR",
   "positionRank": "WR116",
   "team": "CHI",
   "bye": 9,
   "age": "",
   "pts": 14.87,
   "adp": "n/a",
   "vbd": -32.97
 },
 {
   "rank": 283,
   "name": "Jesse James",
   "position": "TE",
   "positionRank": "TE29",
   "team": "PIT",
   "bye": 8,
   "age": "",
   "pts": 22.72,
   "adp": "n/a",
   "vbd": -13.18
 },
 {
   "rank": 284,
   "name": "Jared Goff",
   "position": "QB",
   "positionRank": "QB29",
   "team": "LA",
   "bye": 8,
   "age": "",
   "pts": 63.7,
   "adp": "n/a",
   "vbd": -33.94
 },
 {
   "rank": 285,
   "name": "Mike Davis",
   "position": "RB",
   "positionRank": "RB87",
   "team": "SF",
   "bye": 8,
   "age": "",
   "pts": 16.5,
   "adp": "n/a",
   "vbd": -33.19
 },
 {
   "rank": 286,
   "name": "Eli Rogers",
   "position": "WR",
   "positionRank": "WR117",
   "team": "PIT",
   "bye": 8,
   "age": "",
   "pts": 14.79,
   "adp": "n/a",
   "vbd": -33.05
 },
 {
   "rank": 287,
   "name": "Tyler Higbee",
   "position": "TE",
   "positionRank": "TE30",
   "team": "LA",
   "bye": 8,
   "age": "",
   "pts": 22.4,
   "adp": "n/a",
   "vbd": -13.5
 },
 {
   "rank": 288,
   "name": "Sam Bradford",
   "position": "QB",
   "positionRank": "QB30",
   "team": "PHI",
   "bye": 4,
   "age": "",
   "pts": 62.79,
   "adp": "n/a",
   "vbd": -34.84
 },
 {
   "rank": 289,
   "name": "Wendell Smallwood",
   "position": "RB",
   "positionRank": "RB88",
   "team": "PHI",
   "bye": 4,
   "age": "",
   "pts": 16.16,
   "adp": "n/a",
   "vbd": -33.53
 },
 {
   "rank": 290,
   "name": "Kenny Bell",
   "position": "WR",
   "positionRank": "WR118",
   "team": "TB",
   "bye": 6,
   "age": "",
   "pts": 14.43,
   "adp": "n/a",
   "vbd": -33.41
 },
 {
   "rank": 291,
   "name": "Jace Amaro",
   "position": "TE",
   "positionRank": "TE31",
   "team": "NYJ",
   "bye": 11,
   "age": "",
   "pts": 20.5,
   "adp": "n/a",
   "vbd": -15.4
 },
 {
   "rank": 292,
   "name": "Dak Prescott",
   "position": "QB",
   "positionRank": "QB31",
   "team": "DAL",
   "bye": 7,
   "age": "",
   "pts": 62.11,
   "adp": "n/a",
   "vbd": -35.52
 },
 {
   "rank": 293,
   "name": "Mike Gillislee",
   "position": "RB",
   "positionRank": "RB89",
   "team": "BUF",
   "bye": 10,
   "age": "",
   "pts": 16,
   "adp": "n/a",
   "vbd": -33.69
 },
 {
   "rank": 294,
   "name": "Malcolm Mitchell",
   "position": "WR",
   "positionRank": "WR119",
   "team": "NE",
   "bye": 9,
   "age": "",
   "pts": 14.03,
   "adp": "n/a",
   "vbd": -33.81
 },
 {
   "rank": 295,
   "name": "Richard Rodgers",
   "position": "TE",
   "positionRank": "TE32",
   "team": "GB",
   "bye": 4,
   "age": "",
   "pts": 20.32,
   "adp": "n/a",
   "vbd": -15.58
 },
 {
   "rank": 296,
   "name": "Paxton Lynch",
   "position": "QB",
   "positionRank": "QB32",
   "team": "DEN",
   "bye": 11,
   "age": "",
   "pts": 51.47,
   "adp": "n/a",
   "vbd": -46.16
 },
 {
   "rank": 297,
   "name": "Raheem Mostert",
   "position": "RB",
   "positionRank": "RB90",
   "team": "CLE",
   "bye": 13,
   "age": "",
   "pts": 15.71,
   "adp": "n/a",
   "vbd": -33.98
 },
 {
   "rank": 298,
   "name": "Andre Johnson",
   "position": "WR",
   "positionRank": "WR120",
   "team": "TEN",
   "bye": 13,
   "age": "",
   "pts": 13.89,
   "adp": "n/a",
   "vbd": -33.95
 },
 {
   "rank": 299,
   "name": "Ladarius Green",
   "position": "TE",
   "positionRank": "TE33",
   "team": "PIT",
   "bye": 8,
   "age": "",
   "pts": 19.74,
   "adp": "n/a",
   "vbd": -16.17
 },
 {
   "rank": 300,
   "name": "Tony Romo",
   "position": "QB",
   "positionRank": "QB33",
   "team": "DAL",
   "bye": 7,
   "age": "",
   "pts": 50,
   "adp": "n/a",
   "vbd": -47.64
 },
 {
   "rank": 301,
   "name": "Denard Robinson",
   "position": "RB",
   "positionRank": "RB91",
   "team": "JAX",
   "bye": 5,
   "age": "",
   "pts": 15.52,
   "adp": "n/a",
   "vbd": -34.17
 },
 {
   "rank": 302,
   "name": "Albert Wilson",
   "position": "WR",
   "positionRank": "WR121",
   "team": "KC",
   "bye": 5,
   "age": "",
   "pts": 13.28,
   "adp": "n/a",
   "vbd": -34.56
 },
 {
   "rank": 303,
   "name": "Cameron Brate",
   "position": "TE",
   "positionRank": "TE34",
   "team": "TB",
   "bye": 6,
   "age": "",
   "pts": 19.61,
   "adp": "n/a",
   "vbd": -16.29
 },
 {
   "rank": 304,
   "name": "Trevor Siemian",
   "position": "QB",
   "positionRank": "QB34",
   "team": "DEN",
   "bye": 11,
   "age": "",
   "pts": 44.75,
   "adp": "n/a",
   "vbd": -52.89
 },
 {
   "rank": 305,
   "name": "Marquise Goodwin",
   "position": "WR",
   "positionRank": "WR122",
   "team": "BUF",
   "bye": 10,
   "age": "",
   "pts": 12.96,
   "adp": "n/a",
   "vbd": -34.88
 },
 {
   "rank": 306,
   "name": "Damien Williams",
   "position": "RB",
   "positionRank": "RB92",
   "team": "MIA",
   "bye": 8,
   "age": "",
   "pts": 12.96,
   "adp": "n/a",
   "vbd": -36.73
 },
 {
   "rank": 307,
   "name": "Lance Kendricks",
   "position": "TE",
   "positionRank": "TE35",
   "team": "LA",
   "bye": 8,
   "age": "",
   "pts": 18.14,
   "adp": "n/a",
   "vbd": -17.76
 },
 {
   "rank": 308,
   "name": "New York Giants DEF",
   "position": "D",
   "positionRank": "TD13",
   "team": "NYG",
   "bye": 8,
   "age": "",
   "pts": 95.2,
   "adp": "n/a",
   "vbd": 0.05
 },
 {
   "rank": 308,
   "name": "New York Giants ST",
   "position": "ST",
   "positionRank": "TD13",
   "team": "NYG",
   "bye": 8,
   "age": "",
   "pts": 95.2,
   "adp": "n/a",
   "vbd": 0.05
 },
 {
   "rank": 309,
   "name": "San Francisco 49ers DEF",
   "position": "D",
   "positionRank": "TD14",
   "team": "SF",
   "bye": 8,
   "age": "",
   "pts": 94.56,
   "adp": "n/a",
   "vbd": -0.59
 },
 {
   "rank": 309,
   "name": "San Francisco 49ers ST",
   "position": "ST",
   "positionRank": "TD14",
   "team": "SF",
   "bye": 8,
   "age": "",
   "pts": 94.56,
   "adp": "n/a",
   "vbd": -0.59
 },
 {
   "rank": 310,
   "name": "Carson Wentz",
   "position": "QB",
   "positionRank": "QB35",
   "team": "PHI",
   "bye": 4,
   "age": "",
   "pts": 34.36,
   "adp": "n/a",
   "vbd": -63.28
 },
 {
   "rank": 311,
   "name": "Houston Texans DEF",
   "position": "D",
   "positionRank": "TD15",
   "team": "HOU",
   "bye": 9,
   "age": "",
   "pts": 94.24,
   "adp": "n/a",
   "vbd": -0.91
 },
 {
   "rank": 311,
   "name": "Houston Texans ST",
   "position": "ST",
   "positionRank": "TD15",
   "team": "HOU",
   "bye": 9,
   "age": "",
   "pts": 94.24,
   "adp": "n/a",
   "vbd": -0.91
 },
 {
   "rank": 312,
   "name": "New York Jets DEF",
   "position": "D",
   "positionRank": "TD15",
   "team": "NYJ",
   "bye": 11,
   "age": "",
   "pts": 94.24,
   "adp": "n/a",
   "vbd": -0.91
 },
 {
   "rank": 312,
   "name": "New York Jets ST",
   "position": "ST",
   "positionRank": "TD15",
   "team": "NYJ",
   "bye": 11,
   "age": "",
   "pts": 94.24,
   "adp": "n/a",
   "vbd": -0.91
 },
 {
   "rank": 313,
   "name": "Devin Smith",
   "position": "WR",
   "positionRank": "WR123",
   "team": "NYJ",
   "bye": 11,
   "age": "",
   "pts": 12.81,
   "adp": "n/a",
   "vbd": -35.03
 },
 {
   "rank": 314,
   "name": "Marcel Reece",
   "position": "RB",
   "positionRank": "RB93",
   "team": "OAK",
   "bye": 10,
   "age": "",
   "pts": 11.89,
   "adp": "n/a",
   "vbd": -37.8
 },
 {
   "rank": 315,
   "name": "Crockett Gillmore",
   "position": "TE",
   "positionRank": "TE36",
   "team": "BAL",
   "bye": 8,
   "age": "",
   "pts": 18,
   "adp": "n/a",
   "vbd": -17.9
 },
 {
   "rank": 316,
   "name": "Dan Carpenter",
   "position": "K",
   "positionRank": "PK13",
   "team": "BUF",
   "bye": 10,
   "age": "",
   "pts": 41.28,
   "adp": "n/a",
   "vbd": 0.11
 },
 {
   "rank": 317,
   "name": "Indianapolis Colts DEF",
   "position": "D",
   "positionRank": "TD17",
   "team": "IND",
   "bye": 10,
   "age": "",
   "pts": 92.16,
   "adp": "n/a",
   "vbd": -2.99
 },
 {
   "rank": 317,
   "name": "Indianapolis Colts ST",
   "position": "ST",
   "positionRank": "TD17",
   "team": "IND",
   "bye": 10,
   "age": "",
   "pts": 92.16,
   "adp": "n/a",
   "vbd": -2.99
 },
 {
   "rank": 318,
   "name": "Adam Vinatieri",
   "position": "K",
   "positionRank": "PK14",
   "team": "IND",
   "bye": 10,
   "age": "",
   "pts": 40.64,
   "adp": "n/a",
   "vbd": -0.53
 },
 {
   "rank": 319,
   "name": "Josh McCown",
   "position": "QB",
   "positionRank": "QB36",
   "team": "CLE",
   "bye": 13,
   "age": "",
   "pts": 26.32,
   "adp": "n/a",
   "vbd": -71.32
 },
 {
   "rank": 320,
   "name": "Mike Nugent",
   "position": "K",
   "positionRank": "PK15",
   "team": "CIN",
   "bye": 9,
   "age": "",
   "pts": 40,
   "adp": "n/a",
   "vbd": -1.17
 },
 {
   "rank": 321,
   "name": "Washington Redskins DEF",
   "position": "D",
   "positionRank": "TD18",
   "team": "WAS",
   "bye": 9,
   "age": "",
   "pts": 92,
   "adp": "n/a",
   "vbd": -3.15
 },
 {
   "rank": 321,
   "name": "Washington Redskins ST",
   "position": "ST",
   "positionRank": "TD18",
   "team": "WAS",
   "bye": 9,
   "age": "",
   "pts": 92,
   "adp": "n/a",
   "vbd": -3.15
 },
 {
   "rank": 322,
   "name": "Jason Myers",
   "position": "K",
   "positionRank": "PK15",
   "team": "JAX",
   "bye": 5,
   "age": "",
   "pts": 40,
   "adp": "n/a",
   "vbd": -1.17
 },
 {
   "rank": 323,
   "name": "Detroit Lions DEF",
   "position": "D",
   "positionRank": "TD19",
   "team": "DET",
   "bye": 10,
   "age": "",
   "pts": 91.52,
   "adp": "n/a",
   "vbd": -3.63
 },
 {
   "rank": 323,
   "name": "Detroit Lions ST",
   "position": "ST",
   "positionRank": "TD19",
   "team": "DET",
   "bye": 10,
   "age": "",
   "pts": 91.52,
   "adp": "n/a",
   "vbd": -3.63
 },
 {
   "rank": 324,
   "name": "Sebastian Janikowski",
   "position": "K",
   "positionRank": "PK17",
   "team": "OAK",
   "bye": 10,
   "age": "",
   "pts": 39.68,
   "adp": "n/a",
   "vbd": -1.49
 },
 {
   "rank": 1000,
   "name": "San Diego Chargers DEF",
   "position": "D",
   "positionRank": "D100",
   "team": "SD",
   "bye": 11,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1001,
   "name": "San Diego Chargers ST",
   "position": "ST",
   "positionRank": "ST100",
   "team": "SD",
   "bye": 11,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1002,
   "name": "Atlanta Falcons DEF",
   "position": "D",
   "positionRank": "D101",
   "team": "ATL",
   "bye": 11,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1003,
   "name": "Atlanta Falcons ST",
   "position": "ST",
   "positionRank": "ST101",
   "team": "ATL",
   "bye": 11,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1004,
   "name": "Oakland Raiders DEF",
   "position": "D",
   "positionRank": "D102",
   "team": "OAK",
   "bye": 10,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1005,
   "name": "Oakland Raiders ST",
   "position": "ST",
   "positionRank": "ST102",
   "team": "OAK",
   "bye": 10,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1006,
   "name": "Chicago Bears DEF",
   "position": "D",
   "positionRank": "D103",
   "team": "CHI",
   "bye": 9,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1007,
   "name": "Chicago Bears ST",
   "position": "ST",
   "positionRank": "ST103",
   "team": "CHI",
   "bye": 9,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1007,
   "name": "Tampa Bay Buccaneers DEF",
   "position": "D",
   "positionRank": "D104",
   "team": "TB",
   "bye": 6,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1008,
   "name": "Tampa Bay Buccaneers ST",
   "position": "ST",
   "positionRank": "ST104",
   "team": "TB",
   "bye": 6,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1009,
   "name": "Dallas Cowboys DEF",
   "position": "D",
   "positionRank": "D105",
   "team": "DAL",
   "bye": 7,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1010,
   "name": "Dallas Cowboys ST",
   "position": "ST",
   "positionRank": "ST105",
   "team": "DAL",
   "bye": 7,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1011,
   "name": "Buffalo Bills DEF",
   "position": "D",
   "positionRank": "D106",
   "team": "BUF",
   "bye": 10,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1012,
   "name": "Buffalo Bills ST",
   "position": "ST",
   "positionRank": "ST106",
   "team": "BUF",
   "bye": 10,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1013,
   "name": "Cleveland Browns DEF",
   "position": "D",
   "positionRank": "D107",
   "team": "CLE",
   "bye": 13,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1014,
   "name": "Cleveland Browns ST",
   "position": "ST",
   "positionRank": "ST107",
   "team": "CLE",
   "bye": 13,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1015,
   "name": "Tennessee Titans DEF",
   "position": "D",
   "positionRank": "D108",
   "team": "TEN",
   "bye": 13,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1016,
   "name": "Tennessee Titans ST",
   "position": "ST",
   "positionRank": "ST108",
   "team": "TEN",
   "bye": 13,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1017,
   "name": "Jacksonville Jaguars DEF",
   "position": "D",
   "positionRank": "D109",
   "team": "JAX",
   "bye": 5,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1018,
   "name": "Jacksonville Jaguars ST",
   "position": "ST",
   "positionRank": "ST109",
   "team": "JAX",
   "bye": 5,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1019,
   "name": "Miami Dolphins DEF",
   "position": "D",
   "positionRank": "D110",
   "team": "MIA",
   "bye": 8,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1020,
   "name": "Miami Dolphins ST",
   "position": "ST",
   "positionRank": "ST110",
   "team": "MIA",
   "bye": 8,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1021,
   "name": "Baltimore Ravens DEF",
   "position": "D",
   "positionRank": "D111",
   "team": "BAL",
   "bye": 8,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1022,
   "name": "Baltimore Ravens ST",
   "position": "ST",
   "positionRank": "ST111",
   "team": "BAL",
   "bye": 8,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1023,
   "name": "New Orleans Saints DEF",
   "position": "D",
   "positionRank": "D112",
   "team": "NO",
   "bye": 5,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 },
 {
   "rank": 1024,
   "name": "New Orleans Saints ST",
   "position": "ST",
   "positionRank": "ST112",
   "team": "NO",
   "bye": 5,
   "age": "",
   "pts": 0,
   "adp": "",
   "vbd": 0
 }
]
